lst = [ '🍇', '🍑', '🍐', '🍊', '🍌', '🍎']
grape = (lst[0])
apple = (lst[5])
grape_minus = (lst[-6])
apple_minus = (lst[-1])
length=len(lst)
print(grape)
print(apple)
print(grape_minus)
print(apple_minus)
print(grape, apple, grape_minus, apple_minus)
print(grape, apple, grape_minus, apple_minus, sep='  ')
print(grape, apple, grape_minus, apple_minus, sep=' - ')
print(grape, apple, grape_minus, apple_minus, sep='\n')
print(length)
